### ISSUE TITLE
How to save in-memory file in OnPartBegin and disk-cached file in OnRequestComplete

### ISSUE THREAD

**Issue by JerryChin** [Revanka/paint-upload#3]
Hey, I want to save small files whose size is not beyond the threshold size in `OnPartBegin `method, and save big ones in `OnRequestComplete `method, currently, it seems there's no way to tell the difference between them.

**What I encountered:**
set threshold size to 1KB, upload 2KB picture, when `OnPartBegin `is invoked, `part.isFinished()` is telling me that the part is finished which is not true!

**What be expected:**
set threshold size to 1KB, upload 2KB picture, when `OnPartBegin `is invoked, `part.isFinished()` should be false.
set threshold size to 1KB, upload 0.5KB picture, when `OnPartBegin `is invoked, `part.isFinished() `should be true.

**Comment by Elopteryx** [comment]
Hi!

Thanks for opening an issue! I currently do not have access to a desktop computer with net access to check this, but I will fix this later.

**Comment by Elopteryx** [comment]
Done, the bugfix will be part of the next release.
