### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by dennishendriksen** [Revanka/paint-upload#4]
Using upload-parser 2.2.0 in a Jetty 9.4.8.v20171121 application (via jetty-maven-plugin) with Java 8u152 results in the following exception:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.github.elopteryx.upload.internal.AsyncUploadParser.parseCurrentItem(AsyncUploadParser.java:104)
	at com.github.elopteryx.upload.internal.AsyncUploadParser.onDataAvailable(AsyncUploadParser.java:82)
	at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:426)
```

Could it be that upload-parser 2.2.0 was compiled [using Java 9 with Java 8 as target JDK](http://mail-archives.apache.org/mod_mbox/lucene-dev/201503.mbox/%3C07c401d06aba$0b477c80$21d67580$@thetaphi.de%3E
)?

**Comment by Elopteryx** [comment]
Hi! Thanks for this, you are right, the build used the JDK9 for publishing that version.
I can see that the ByteBuffer class itself got the position method defined in Java 9, instead of inheriting it from the Buffer class.
There isn't much to do, I will release a bugfix version, using Java 8u152.

**Comment by Elopteryx** [comment]
The 2.2.1 release solves the issue.

**Comment by dennishendriksen** [comment]
Thank you for the quick reply and fix! Looking forward to playing around further with your upload-parser.
